config/routes.rb
Rails.application.routes.draw do
  root controller: :products, action: :index
  resources :products, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord


end

app/models/product.rb
class Product < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @query = params[:query]
    @attribute = params[:attribute]
    @unsafe_mode = params[:unsafe_mode] == "1"
    @products = Products::ProductSearch.new(@query, @attribute, unsafe_mode: @unsafe_mode).search 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnsafeHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="product-list">
  <h1> Products </h1>
  <%= form_with url: products_path, method: :get, class: "product-search" do |form| %>

    <div class="search-field">
      <%= form.label :query, "Search product names:" %>
      <div class="product-search-bar">
        <%= form.text_field :query, value: @query %>
      </div>
    </div>
    <div class="search-field">
      <%= form.label :attribute, "Search product attribute:" %>
      <div class="product-search-bar">
        <%= form.select :attribute,  Product.column_names.dup.prepend(@attribute.to_s).uniq %>
      </div>
    </div>
     <div class="search-field">
      <%= form.label :unsafe_mode, "Super unsafe mode" %>
      <div class="product-search-bar">
        <%= form.check_box :unsafe_mode, checked: @unsafe_mode %>
      </div>
    </div>
    <%= form.submit "Unsafe search" %>
  <% end %>
  <%= render partial: "products/index/product", collection: @products %>
</div>

app/views/products/index/_product.html.erb
<div class="product">
  <% product.each do |attr| %>
    <div class="attribute">
      <p><strong><%= attr.first %>:</strong></p>
      <p><%= attr.second%></p>
    </div>
  <% end %>
</div>